# Generated by Django 3.2.5 on 2021-07-17 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+8801', max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('name', models.CharField(max_length=200)),
                ('delivary', models.CharField(choices=[('R', 'Regular'), ('E', 'Express')], max_length=10)),
                ('store', models.CharField(max_length=200)),
                ('prescription_file', models.ImageField(upload_to='prescription/')),
                ('apartment', models.CharField(max_length=250)),
                ('House', models.CharField(max_length=250)),
                ('Road', models.CharField(max_length=250)),
                ('Area', models.CharField(max_length=250)),
            ],
        ),
    ]
