# Generated by Django 3.2.5 on 2021-07-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_prescription_api', '0003_alter_upload_prescription_prescription_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_prescription',
            name='phone',
            field=models.CharField(max_length=16),
        ),
    ]
