# Generated by Django 3.2.5 on 2021-07-18 07:34

from django.db import migrations, models
import upload_prescription_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('upload_prescription_api', '0004_alter_upload_prescription_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_prescription',
            name='prescription_file',
            field=models.FileField(blank=True, null=True, upload_to='prescription/', validators=[upload_prescription_api.validators.validate_file_extension]),
        ),
    ]
